### PR TITLE
Upgrade PureScript 0.14

### PR DESCRIPTION
**Pull request by ad-si**
I removed the function `readYAMLGeneric` since `foreign-generic` will probably not be upgraded to 0.14. Since this package isn't really distributed anywhere currently, I don't think it's a problem that it's a breaking change. Could be reimplemented in a future version with the default generics I guess.

I'd release a new version once this merged and add it to package-sets, ok?

### CODE REVIEW

**Comment by dgendill** [comment]
Thanks, Adrian!

**Comment by dgendill** [comment]
I tag a new version as 3.0.0

**Comment by ad-si** [comment]
@dgendill Thanks! Next time we release a new version we need, however, use `spago bump-version --no-dry-run major` to create the new version since it automatically creates the corresponding `bower.json` file. This is necessary for publishing to Pursuit. I just released a new version v3.0.1 to fix this.
Also I just pushed directly to master. Is this OK with you @dgendill and @archaeron or shall I always open PRs?

**Comment by dgendill** [comment]
Hey, Adrian, sorry about that about! I misunderstand the process for the release.

Yes, merging to master is fine with me. Also, unless @archaeron has objections, I'm ok with you merging your own PRs. I haven't use PureScript for a while, so I probably shouldn't be involved at all 😂

**Comment by archaeron** [comment]
merging to master means no errors allowed :D

but it's up to you. I sadly haven't been able to use PureScript for a while too :(

**Comment by ad-si** [comment]
Errors? In my code? Never! 😜
Next time I change something I'll add CI to make it at least a little more robust.

**Pull request merged**
