### PR TITLE
parseYAMLToJson, instances for StrMap and Map

### PR DESCRIPTION
**Pull request by dgendill**
This PR adds a hook so users can go from YAML to Argonaut's Json type - that way they can do their data marshalling in Argonaut instead of Foreign.  Also I added ToYAML instances for `StrMap` and `Map String`.

### CODE REVIEW

**Comment by pallix** [comment]
How will the decode work for these new types?

**Comment by dgendill** [comment]
After IsForeign was removed from purescript-foreign, it's my understanding that purescript-argonaut is considered the best way to decoding now.  So you would use parseYAMLToJson to get to `Json`, and then decode using Argonaut functionality after that.  Then use the IsYAML instances take your purescript data back into yaml.

Here's an example using the Point data type from the tests.

```purescript
yamlPoint :: String
yamlPoint = """
X: 1
Y: 1
"""

getPoint :: Either String Point
getPoint = case runExcept $ parseYAMLToJson yamlPoint of
  Left err -> Left "Could not parse yaml"
  Right json -> decodeJson json

instance pointJson :: DecodeJson Point where
  decodeJson s = do
    obj <- maybe (Left "Point is not an object.") Right (toObject s)
    x <- getField obj "X"
    y <- getField obj "Y"
    pure $ Point x y
```

**Comment by dgendill** [comment]
I'm going to close this, @archaeron.  I added some documentation and some other changes on my master fork, so this PR has some extra stuff in it now.  Let me know if you'd like to merge any my changes and I'll reopen it.

**Comment by archaeron** [comment]
@dgendill I will merge it if you say it's ready and it works. unfortunately I don't work with PS at the moment, so I don't have the time to work on this. But I gladly accept PRs.

**Pull request closed without merging**
